#-------------------------------
# General Site Settings

title: JH Fotos
description: Concert & Portrait
email: jannis@jh-fotos.de

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Über, url: '#about-me'}
- {name: Projekte, url: '#work'}
- {name: Referenzen, url: '#clients'}
- {name: Kontakt, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Offizielle Website von Jannis Hinkelmann, Fotograf aus Lauterecken'
  rel-author: 'https://plus.google.com/u/0/115849271503758637116/'
  rel-publisher: 'https://plus.google.com/u/0/115849271503758637116/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Jannis fotografiert leidenschaftlich** *Konzert* und *Portrait*.
  Dabei liegt sein Fokus auf der Schaffung bleibender Erinnerungen für andere.
  Er geht aber auch gerne seinen eigenen Ideen nach und postet Natur- und Landschaftsbilder.

# skills:
#- {name: Ideen & Kreativität, value: 5}
#- {name: Kommunikation, value: 7}
#- {name: Bildgestaltung, value: 8}
#- {name: Nachbearbeitung, value: 6}
#- {name: Lernfähigkeit, value: 7}
#- {name: Zuverlässigkeit, value: 9}
#-------------------------------
# Work Section

projects:

- {name: Herbstfarben, folder: 'jessi', file: 'work/proj-jessi.html', thumb: 'thumb.jpg'}
- {name: Sommerabend-Stimmung, folder: 'anna', file: 'work/proj-anna.html', thumb: 'thumb.jpg'}
- {name: FadeOut, folder: 'fadeoutphoto', file: 'work/proj-fadeoutphoto.html', thumb: 'thumb.jpg'}
- {name: Broken Honesty, folder: 'brokenhonesty', file: 'work/proj-brokenhonesty.html', thumb: 'thumb.jpg'}
- {name: Brixten, folder: 'brixten', file: 'work/proj-brixten.html', thumb: 'thumb.jpg'}
- {name: Videodreh mit FadeOut, folder: 'fadeoutvideo', file: 'work/proj-fadeoutvideo.html', thumb: 'thumb.jpg'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'thomas.jpg',
  name: 'Thomas Schütz',
  title: 'Geschäftsführer, <a href="http://www.schuetz-sound-and-light.de/" target="_blank">Schütz Sound&Light</a>',
  quote: '<p><strong>Bei einem Projekt ist eine gute Absprache</strong> und eine super Zusammenarbeit wichtig für den Erfolg. Diese Punkte setzt Jannis jederzeit zu 100% um und entwickelt so ein einmaliges Ergebnis.</p>',
  logo: 'schuetz-logo.png'}
- {avatar: 'jackdice.jpg',
  name: 'Jack Dice',
  title: 'Gitarrist, <a href="http://www.fadeout-rock.de/" target="_blank">FadeOut Rock Cover</a>',
  quote: '<p><strong>Mit Jannis kann man einfach wunderbar zusammenarbeiten.</strong> Durch seinen Sinn fürs Detail und seine Kreativität, die er bei jedem Projekt individuell mit einfließen lässt, entsteht bei jedem Foto und jedem Video ein kleines Kunstwerk.</p>',
  logo: 'fadeout-logo.png'}
- {avatar: 'flo.jpg',
  name: 'Florian Schmidt',
  title: 'Mitgründer, <a href="https://qugit.net/" target="_blank">QugIT GbR</a>',
  quote: '<p><strong>Jannis setzt jeden in ein gutes Licht.</strong> Bei Ihm erhält man das rundum sorglos Paket. Sogar aus einem chaotischen Haufen wie uns hat er das Beste rausgeholt und super Bilder gemacht.</p>',
  logo: 'qugit-logo.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/j_hinkelmann'}
- {icon: 'facebook', link: 'https://facebook.com/jhfotosde'}
- {icon: 'instagram', link: 'https://www.instagram.com/j_hinkelmann/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
