#-------------------------------
# General Site Settings

title: JH Fotos
description: Fotografie // Videografie
email: jannis@jh-fotos.de

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Über, url: '#about-me'}
- {name: Projekte, url: '#work'}
- {name: Partner, url: '#clients'}
- {name: Kontakt, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Offizielle Website von Jannis Hinkelmann, Fotograf aus Lauterecken'
  rel-author: 'https://plus.google.com/u/0/115849271503758637116/'
  rel-publisher: 'https://plus.google.com/u/0/115849271503758637116/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Jannis fotografiert leidenschaftlich** *Events* und *Portrait*.
  Dabei liegt sein Fokus in der Schaffung bleibender Erinnerungen für andere.
  Er geht aber auch gerne seinen eigenen Ideen nach und postet Natur- und Landschaftsbilder.

skills:
- {name: Ideen & Kreativität, value: 5}
- {name: Kommunikation, value: 7}
- {name: Bildgestaltung, value: 8}
- {name: Nachbearbeitung, value: 6}
- {name: Lernfähigkeit, value: 7}
- {name: Zuverlässigkeit, value: 9}

#-------------------------------
# Work Section

projects:

- {name: Herbstfarben, folder: 'jessi', file: 'work/proj-jessi.html'}
- {name: Sommerabend-Stimmung, folder: 'anna', file: 'work/proj-anna.html'}
- {name: FadeOut, folder: 'fadeoutphoto', file: 'work/proj-fadeoutphoto.html'}
- {name: Broken Honesty, folder: 'brokenhonesty', file: 'work/proj-brokenhonesty.html'}
- {name: Brixten, folder: 'brixten', file: 'work/proj-brixten.html'}
- {name: Videodreh mit FadeOut, folder: 'fadeoutvideo', file: 'work/proj-fadeoutvideo.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'thomas.jpg',
  name: 'Thomas Schütz',
  title: 'Geschäftsführer, <a href="http://www.schuetz-sound-and-light.de/" target="_blank">Schütz Sound&Light</a>',
  quote: '<p><strong>Inmensae subtilitatis, obscuris</strong> et malesuada fames. Quam diu etiam furor iste tuus nos eludet? Quisque ut dolor gravida, placerat libero vel, euismod. Mercedem aut nummos unde unde extricat, amaras.</p>',
  logo: 'schuetz-logo.png'}
- {avatar: 'rene.jpg',
  name: 'René Grub',
  title: 'Gitarrist, <a href="http://www.fadeout-rock.de/" target="_blank">FadeOut Rock Cover</a>',
  quote: '<p><strong>Fabio vel iudice vincam, sunt in culpa qui officia.</strong> Etiam habebis sem dicantur magna mollis euismod. Ut enim ad minim veniam, quis nostrud exercitation.</p>',
  logo: 'fadeout-logo.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/j_hinkelmann'}
- {icon: 'facebook', link: 'https://facebook.com/jannishinkelmann'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
